# Generated by Django 4.2.2 on 2023-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('lifespan', models.IntegerField()),
                ('population', models.CharField(max_length=100)),
            ],
        ),
    ]
